---

# tasks file for firefox_config


# TODO make idempotent
- name: Create firefox profile
  ansible.builtin.command: 
    cmd: "firefox -headless -CreateProfile {{ profile_name }}"
  register: result
  changed_when: result.rc == 0

- name: Populate default profile
  ansible.builtin.command: firefox -headless -P default_profile_by_ansible
  async: 1
  poll: 1
  ignore_errors: true

- name: Find profile directory
  ansible.builtin.find:
    paths: "{{ firefox_config_path[ansible_distribution] }}"
    patterns: '*.{{ profile_name }}'
    file_type: directory
  register: profile_dir

- name: Parse result for profile path
  set_fact:
    profile_path: "{{ profile_dir.files[0].path }}"

- name: Show profile path
  ansible.builtin.debug:
    var: profile_path

- name: Copy user.js to host
  ansible.builtin.copy:
    src: "{{ user_config_file }}"
    dest: "{{ profile_path }}/{{ user_config_file }}"
    mode: preserve

- name: Set general options in profiles.ini
  loop: "{{ profile_options | dict2items }}"
  community.general.ini_file:
    path: '{{ firefox_config_path[ansible_distribution] }}/profiles.ini'
    section: General
    option: '{{ item.key }}'
    value: '{{ item.value }}'
    mode: 0644
    create: yes
    no_extra_spaces: yes

- name: Set ansible profile name
  loop: "{{ profile_config | dict2items }}"
  community.general.ini_file:
    path: "{{ firefox_config_path[ansible_distribution] }}/profiles.ini"
    section: Profile0
    option: "{{ item.key }}"
    value:  "{{ item.value }}"
    mode: "0644"
    create: yes
    no_extra_spaces: yes

# TODO loop over extensions
- name: Get extensions
  loop: "{{ extensions }}"
  loop_control:
    loop_var: extension
  ansible.builtin.include_tasks:
    file: extensions.yml

- name: Create directory if they don't exist
  ansible.builtin.file:
    path: "/{{ policies_path }}"
    state: directory
    owner: root
    group: root
    mode: "0775"
  become: true

- name: copy policies.json to host
  ansible.builtin.copy:
    src: "{{ policies_file }}"
    dest: "/{{ policies_path }}/{{ policies_file }}"
    mode: preserve
  become: true

...