---

# tasks to configure firefox settings


- name: Template user.js to host
  ansible.builtin.template:
    src: "user.js.j2"
    dest: "{{ profile_path }}/user.js"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0644"

- name: Create directory if it doesn't exist
  become: true
  ansible.builtin.file:
    path: "/{{ policies_path }}"
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Template policies.json to host - enables extensions
  when: firefox_extensions
  become: true
  ansible.builtin.template:
    src: "policies.json.j2"
    dest: "/{{ policies_path }}/policies.json"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0644"

...