---

- name: "Call Firefox Addons API for theme info for {{ extension.name }}"
  ansible.builtin.uri:
    url: https://addons.mozilla.org/api/v5/addons/addon/{{ extension.id }}
    return_content: true
  register: api_call

- name: Parse result for download link
  ansible.builtin.set_fact:
    theme_download_link: "{{ api_call.json.current_version.file.url }}"

- name: Parse result for guid
  ansible.builtin.set_fact:
    ext_guid: "{{ api_call.json.guid }}"

- name: Ensure extensions directory exists
  become: true
  ansible.builtin.file:
    path: "{{ firefox_system_ext_dir[firefox_source][ansible_os_family] }}"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"

- name: Download theme extension file
  become: true
  ansible.builtin.get_url:
    url: "{{ theme_download_link }}"
    dest: "{{ firefox_system_ext_dir[firefox_source][ansible_os_family] }}/{{ ext_guid }}.xpi"
    mode: "0644"
    owner: "root"
    group: "root"

...
