---

# tasks to install ansible-firefox


- name: Install debian specific package_facts dependency
  become: true
  when: ansible_distribution == "Debian"
  ansible.builtin.package:
    name: python-apt-common
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Install Firefox
  when: firefox_package[ansible_os_family] not in ansible_facts.packages
  ansible.builtin.include_tasks:
    file: "{{ firefox_source }}.yml"

- name: Setup firefox default profile
  ansible.builtin.include_tasks:
    file: profile.yml

- name: Get extensions
  when: firefox_extensions
  loop: "{{ extensions }}"
  loop_control:
    loop_var: extension
  ansible.builtin.include_tasks:
    file: extensions.yml

- name: Configure firefox
  ansible.builtin.include_tasks:
    file: config.yml

- name: Add firefox to gnome favorites
  when: gnome_favorite
  ansible.builtin.include_tasks:
    file: favorite.yml

...
