---

- name: Install debian specific package_facts dependency
  become: true
  when: ansible_distribution == "Debian"
  ansible.builtin.package:
    name: python-apt-common
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Remove default snap install from Ubuntu
  when: "'snapd' in ansible_facts.packages"
  ansible.builtin.include_tasks:
    file: purge_snap.yml

- name: Install Firefox
  ansible.builtin.include_tasks:
    file: "{{ firefox_source }}.yml"

...
