---

# tasks to install ansible-firefox
# INFO larger roles should only use **include_tasks** here


# INFO This task may be osbolete for your use-case
- name: Gather package facts
  ansible.builtin.package_facts:

...
