---

- name: Check for supported install source
  when: firefox_source not in ["default", "esr", "flatpak"]
  ansible.builtin.fail:
    msg: "Please change {{ firefox_source }} to one of the supported ones: default, esr or flatpak"

- name: Install debian specific package_facts dependency
  become: true
  when: ansible_distribution == "Debian"
  ansible.builtin.package:
    name: python-apt-common
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Remove default snap install from Ubuntu
  when: "'snapd' in ansible_facts.packages"
  ansible.builtin.include_tasks:
    file: purge_snap.yml

- name: Install Firefox
  ansible.builtin.include_tasks:
    file: "{{ firefox_source }}.yml"

- name: Install extensions system-wide
  when: firefox_extensions_enabled and firefox_source != "flatpak"
  loop: "{{ firefox_extensions }}"
  loop_control:
    loop_var: extension
    label: "{{ extension.name }}"
  ansible.builtin.include_tasks:
    file: extensions.yml

...
