---

# tasks to install ansible-firefox


- name: Install debian specific package_facts dependency
  become: true
  when: ansible_distribution == "Debian"
  ansible.builtin.package:
    name: python-apt-common
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Include dependencies
  ansible.builtin.include_tasks:
    file: dependencies.yml

- name: Install firefox
  become: true
  when: firefox_package[ansible_os_family] not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ firefox_package[ansible_os_family] }}"
    state: present

- name: Configure firefox
  ansible.builtin.include_tasks:
    file: config.yml

...
