---

- name: Ensure /etc/apt/keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Mozilla GPG key
  become: true
  ansible.builtin.get_url:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    dest: /etc/apt/keyrings/packages.mozilla.org.asc
    mode: '0644'

- name: Ensure root's .gnupg directory exists
  become: true
  ansible.builtin.file:
    path: /root/.gnupg
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Add Mozilla APT repository with signed-by
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/mozilla.list
    line: 'deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main'
    create: true
    state: present
    mode: '0644'

- name: Set APT pinning preference for packages.mozilla.org
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/mozilla
    content: |
      Package: *
      Pin: origin packages.mozilla.org
      Pin-Priority: 1000
    mode: '0644'

- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

...
