---

- name: Test installed package
  when: firefox_source in ["default", "esr"]
  ansible.builtin.assert:
    that:
      - firefox_package[firefox_source][ansible_os_family] in ansible_facts.packages
    fail_msg: "Package '{{ firefox_package[firefox_source][ansible_os_family] }}' is not installed"
    quiet: true

- name: Test installed firefox flatpak
  when: firefox_source == "flatpak"
  block:
    - name: Check if Flatpak Firefox is installed
      become: true
      ansible.builtin.command: flatpak list --app --columns=application
      register: flatpak_apps
      changed_when: false
      failed_when: false

    - name: Assert Firefox Flatpak is installed
      ansible.builtin.assert:
        that:
          - "'org.mozilla.firefox' in flatpak_apps.stdout_lines"
        fail_msg: "Firefox Flatpak is NOT installed."
        quiet: true

...
