---

- name: Create and configure ansible-nautilus
  hosts: client

  # TODO local testing only
  # debugger: on_failed

  roles:
    - role: ansible-firefox
      tasks_from: main
      firefox_state: present
      enable_plugins: true

...
