---

- name: Verify
  hosts: client

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Initialize role library
      ansible.builtin.include_role:
        name: ansible-firefox
        tasks_from: tests

...
